### ISSUE TITLE
The kubectl build tagged v1.18.4 is broken

### ISSUE THREAD

**Issue by cannontrodder** [lachie83/k8s-kubectl#130]
Hi, just thought I'd report back. Thanks for the builds, I like to use these to bootstrap our own toolkits but I always pin a specific version rather than pull latest. The image tagged v1.18.4 must have experienced a network issue during build as the kubectl 'binary' is an xml file with an error in it. You'll see that the image size is around 3MB rather than the usual 15 or so. Probably worth untagging this one :-)

**Comment by lachie83** [comment]
Thanks for the report. I'll see if I can trigger another push from the branch and get it fixed

**Comment by lachie83** [comment]
Rebuilt v1.18.4 container from https://github.com/lachie83/k8s-kubectl/commit/bfcc9f9b05e9bc2e763d71ed572055a6d50d629c.

```
$ docker run lachlanevenson/k8s-kubectl:v1.18.4 version --client
Unable to find image 'lachlanevenson/k8s-kubectl:v1.18.4' locally
v1.18.4: Pulling from lachlanevenson/k8s-kubectl
df20fa9351a1: Already exists
f62c6e2d0ff0: Pull complete
Digest: sha256:a14cbd023f72ef78091acc437dc240d7aa1fcb37e80d43d7eacc025250067d0e
Status: Downloaded newer image for lachlanevenson/k8s-kubectl:v1.18.4
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Let me know if you're still having issues with this container.
