### ISSUE TITLE
kubecltl ARM Support

### ISSUE THREAD

**Issue by wep4you** [lachie83/k8s-kubectl#138]
Because of the switch from apple to ARM and also the new Raspberry Pi 4 with 8GB of ram, it would be nice to also have a multi arch image. Are there any plans to provide this in the future?

**Comment by wep4you** [comment]
Started a fork of your Repo https://github.com/wep4you/k8s-kubectl and managed to get a multiarch build with GitHub-Actions for the latest version https://hub.docker.com/r/wep4you/k8s-kubectl

**Comment by lachie83** [comment]
Hi @wep4you. This is excellent! Would you be interested on contributing the GH Action back? I would be happy to migrate this over to GH Action

**Comment by wep4you** [comment]
@lachie83 Sure should I start a PR, after I have merged the latest version into my fork?

**Comment by lachie83** [comment]
Yeah that sounds good! Thanks

**Comment by mockersf** [comment]
Hello @wep4you, any chance of a PR? Or can I continue from your fork?

**Comment by wep4you** [comment]
@mockersf Had no time for the PR, I'm fine if you wan't to take over. Should be not much effort.

**Comment by lachie83** [comment]
Just had the contributions to another image I maintain - https://github.com/lachie83/k8s-helm/pull/89. I will get this done when I have time

**Comment by lachie83** [comment]
Added ARM arch support for image tags latest and version >= v1.21.1. Please try it out.
