### ISSUE TITLE
Openssl Issue in kubectl 1.2.5 based on alpine 3.4

### ISSUE THREAD

**Issue by tsupertramp** [lachie83/k8s-kubectl#14]
Hey Ho,

first of all thanks for your maintenance work!

I wanted to use your image with tag 1.2.5 but it always throws:
```Unable to connect to the server: x509: failed to load system roots and no roots provided```

This is caused by alpine 3.4 and the way you install the ca-certificates. They get removed
with the rest of the deps. (e.g. check https://github.com/docker-library/golang/issues/97 - They have the same problem).

A proper workaround and quick fix for me is represented in:
https://github.com/tsupertramp/dockerimage-kubectl-1.2.5

Greetings, Thomas

**Comment by lachie83** [comment]
Hi Thomas! Thank you very much for raising an issue sorry for the delayed response. I've pushed the fix into v1.2.5 branch if you would like to take a look.

https://github.com/lachie83/k8s-kubectl/blob/v1.2.5/Dockerfile

**Comment by tsupertramp** [comment]
Your branch works 👍  Thanks for fixing it!
