### ISSUE TITLE
 Failed to pull image "lachlanevenson/k8s-kubectl:v1.18.20": rpc error: code = Unknown desc = Error response from daemon: manifest for lachlanevenson/k8s-kubectl:v1.18.20 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by rashminair90** [lachie83/k8s-kubectl#157]
Failed to pull image "lachlanevenson/k8s-kubectl:v1.18.20": rpc error: code = Unknown desc = Error response from daemon: manifest for lachlanevenson/k8s-kubectl:v1.18.20 not found: manifest unknown: manifest unknown

Can you please build and make this image available?

**Comment by lachie83** [comment]
Thanks. I just noticed the build failed for that branch due to a transient error with packages on a specific platform. I just reran the jump and it was successful. This should be fixed.
