### ISSUE TITLE
change current working directory to /root

### ISSUE THREAD

**Issue by rajatjindal** [lachie83/k8s-kubectl#62]
I am trying to use this image to run kubectl commands and as part of that I want to mount my current working directory to current working directory of the container

something like this:

KUBECTL="docker run -v `pwd`:/root -v ${KUBECONFIG}:${KUBECONFIG} lachlanevenson/k8s-kubectl --kubeconfig $KUBECONFIG"

Now I can run kubectl commands as if I am running it on my local machine

for file in `find manifests/$ENVIRONMENT/tests -name *.yaml`; do
  $KUBECTL delete -f $file -n $namespace
  $KUBECTL create -f $file -n $namespace
done

**Comment by m247support** [comment]
@rajatjindal Thanks for this example. Can you please clarify what volume for $KUBECONFIG should be? Are you mounting /etc/kubernetes/admin.conf or ~/.kube/config?

**Comment by rajatjindal** [comment]
it can be any directory. e.g. in my case I use jenkins credentials, which expose the kubeconfig file as a completely random location and then I use it something like follows:

KUBECONFIG=/some/random/dir/config
docker run -v $KUBECONFIG:$KUBECONFIG lachlanevenson/k8s-kubectl --kubeconfig $KUBECONFIG

**Comment by lachie83** [comment]
Thanks for raising this. Does this help? #66

**Comment by rajatjindal** [comment]
yes, that would help. thanks a lot man. you guys are awesome

**Comment by lachie83** [comment]
Great. Merged

**Comment by Quentin-M** [comment]
https://github.com/lachie83/k8s-kubectl/pull/66#issuecomment-435196597
