### ISSUE TITLE
default account deployment forbidden...

### ISSUE THREAD

**Issue by tengzhexiao** [lachie83/k8s-kubectl#67]
When I use the image in .gitlab-ci.yml 
....
k8s-deploy:
  stage: deploy
  script:
  - kubectl version
  - kubectl apply -f deployment.yml
....

the container report error as follows.
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc4200f69c0 0xc4202159d0 gitlab helloFormGitlab deployment.yml 0xc420f61b90  false}
from server for: "deployment.yml": deployments.apps "helloFormGitlab" is forbidden: User "system:serviceaccount:gitlab:default" cannot get deployments.apps in the namespace "gitlab"

could you tell me how to let it to work?
I try to overwrite service account but It's cannot work too... :
  #KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: gitlab-runner
  #KUBERNETES_SERVICE_ACCOUNT: "gitlab-runner"

**Comment by lachie83** [comment]
This is due to Kubernetes RBAC. You will need to create a service account. Attach it to the pod and create the associate role and rolebindings to allow access get deployments in that namespace

**Comment by lachie83** [comment]
This issue isn't actual due to the container.

**Comment by tengzhexiao** [comment]
thanks a lot ,that's ok!
