### ISSUE TITLE
Way to use it to run commands from within cluster

### ISSUE THREAD

**Issue by cmosgh** [lachie83/k8s-kubectl#79]
Hi there Lachlan

I am trying to build a administrative tool for our cluster in nodeJS.

The client libraries that exists aren't really helpful because the most important part for me (exec) doesn't work or not properly.

Do you have any idea on how I would go into running commands on the k8s-kubectl container in the pod from my nodejs container.

Or maybe I should create a separate docker container with nodejs and kubectl for it?
The thing is I don't want to create large docker containers. I would reuse any that is already small.

What bothers me mostly tho is that I am using the container in my Jenkins builds but I don't understand yet how does Jenkins run commands inside the container.

**Comment by lachie83** [comment]
How about using a podTemplate in Jenkins running the commands inside that. For example - https://github.com/lachie83/croc-hunter/blob/master/Jenkinsfile#L10

**Comment by cmosgh** [comment]
I know how and ca run it on Jenkins, that is not an issue. In my case the idea is that I want to run commands from a nodejs app without creating a new Docker image i.e. with nodejs and kubectl inside.
So I start my node app container and somehow run commands on the kubectl container in the same pod.

**Comment by lachie83** [comment]
I'm not sure that's possible without having the kubectl binary/client library in your nodejs app. The only thing I've done before is place kubectl as another container in a pod then run 'kubectl proxy' to manage connectivity to the k8s api server but you still need your nodejs app to talk via that socket

**Comment by cmosgh** [comment]
Just for the sake of closure. The solution that worked in the end was by using https://github.com/kubernetes-client/javascript and its exec implementation that works via websockets

**Comment by cmosgh** [comment]
And i used if for i.e. doing mongodump and streaming that dbdump in a web client
