### ISSUE TITLE
Unable to connect to the server: x509:

### ISSUE THREAD

**Issue by magick93** [lachie83/k8s-kubectl#91]
When I run the following

```
 docker run --rm lachlanevenson/k8s-kubectl:v1.12.2 --server=myk8scluster.com get pods --insecure-skip-tls-verify=true

```

I get the following error:

```
Unable to connect to the server: x509: certificate signed by unknown authority
```

Any idea what that is?

**Comment by lachie83** [comment]
@magick93 Did you get to the bottom of this issue here? I'm unable to replicate

**Comment by magick93** [comment]
No, I didnt.

**Comment by MikkelHJuul** [comment]
@magick93 try the flag  `--certificate-authority` and point at valid certificate. 

@lachie83 this should be safe to close; this is not an issue with this project

**Comment by lachie83** [comment]
Thanks @MikkelHJuul. Closing for now
