### ISSUE TITLE
How to replace variables with this image before deploying?

### ISSUE THREAD

**Issue by zedtux** [lachie83/k8s-kubectl#98]
I have some dynamic values in my YAML files and I checked your image and it doesn't include the `envsubst` command I wanted to use to update the files before to run the apply command.

So do you have a way to replace values in the YAML file using this Docker image?

**Comment by the-horhe** [comment]
What's the status on it? Have the same issue. Would be super nice to have `envsubst` in container.

**Comment by papko26** [comment]
Workaround, before we built our own image with envsbust for me was installing gettext packet when running CI script based on this image:
 image: lachlanevenson/k8s-kubectl
 script:
  - apk update && apk add gettext
  ...
  - cat k8s/deployment.yaml | envsubst > k8s-deployment.yaml
  - kubectl -n $DEPLOY_NAMESPACE apply -f k8s-deployment.yaml
  ...
Hope this may help.

**Comment by the-horhe** [comment]
Definitely legit workaround, but in my case i can't use custom image.

Found another possible solution with eval here (second popular answer):
https://unix.stackexchange.com/questions/294835/replace-environment-variables-in-a-file-with-their-actual-values/294840

If you are using it in jenkins pipelines it will looks smth like this:
sh "eval \"echo \\\"\$(cat k8s/deployment.yml)\\\"\" | kubectl --namespace='${NAMESPACE}' apply -f -"

Super ugly but works well in my test env.

**Comment by MikkelHJuul** [comment]
@papko26 @zedtux @the-horhe  you might just want another container in stead? I use my own: mjuul/variations-on-a-k
Which is based on bitnami/kubectl where I use `envsubst` and `yq`.

Sorry for the blatant commercial of my own image there may be other images out there collecting those tools (bash, envsubst, kubectl)

I will rebase the image soon to use kubectl from this container (which also updates the kubectl version) and I may just switch to dasel in stead of yq and write the script variations-on-a-k as a program in go using dasel internally in stead.

I really don't think this container should implement this, it should remain focused

**Comment by lachie83** [comment]
Thanks @MikkelHJuul. As you mentioned, I would like to keep the scope of this container to simply kubectl. Feel free to fork and add things as you see fit.

**Comment by zedtux** [comment]
You could have shared your workaround while close this issue 😏

**Comment by MikkelHJuul** [comment]
> You could have shared your workaround while close this issue

FROM ubuntu
RUN \
  apt update \
  && apt -y install gettext-base curl \
  && apt clean \
  && rm -rf /var/lib/apt/lists/* \
  && mkdir /root/.kube && ln -s /root/.kube /.kube

COPY --from=mikefarah/yq /usr/bin/yq /usr/bin/yq  //used by my own script
COPY --from=lachlanevenson/k8s-kubectl /usr/local/bin/kubectl /usr/local/bin/kubectl
COPY variations-on-a-k /usr/bin/
WORKDIR /root

ENTRYPOINT ["variations-on-a-k"]

**Comment by zedtux** [comment]
Thank you, that's your workaround. I just wanted to know what @lachie83 recommends. Maybe he will recommend yours, I don't know. But again, thank you :)
